"""añadiendo ingredietnes tamano

Revision ID: 0f8313265fab
Revises: 70a29e35f41a
Create Date: 2026-03-15 12:14:42.806667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8313265fab'
down_revision = '70a29e35f41a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingrediente_tamano',
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('tamano_id', sa.Integer(), nullable=False),
    sa.Column('precio_extra', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.ForeignKeyConstraint(['tamano_id'], ['tamanos.id'], ),
    sa.PrimaryKeyConstraint('ingrediente_id', 'tamano_id')
    )
    with op.batch_alter_table('detalle_extras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tamano_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tamanos', ['tamano_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_extras', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tamano_id')

    op.drop_table('ingrediente_tamano')
    # ### end Alembic commands ###
