"""añadiendo notas

Revision ID: 112adc6636d2
Revises: 8161b77195e6
Create Date: 2026-04-05 12:50:30.216875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112adc6636d2'
down_revision = '8161b77195e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_pedido', schema=None) as batch_op:
        batch_op.drop_column('notas')

    # ### end Alembic commands ###
