"""añadiendo mitades

Revision ID: 8161b77195e6
Revises: 0f8313265fab
Create Date: 2026-03-18 21:35:54.436603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8161b77195e6'
down_revision = '0f8313265fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalle_mitad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detalle_id', sa.Integer(), nullable=False),
    sa.Column('mitad', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['detalle_id'], ['detalle_pedido.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_mitad_extra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detalle_mitad_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['detalle_mitad_id'], ['detalle_mitad.id'], ),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detalle_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_mitad', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_pedido', schema=None) as batch_op:
        batch_op.drop_column('is_mitad')

    op.drop_table('detalle_mitad_extra')
    op.drop_table('detalle_mitad')
    # ### end Alembic commands ###
